# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-18 14:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone number')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('status', models.CharField(choices=[(b'CL', b'Call later'), (b'AW', b'Not responding')], max_length=10, verbose_name='Status')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('processing_date', models.DateTimeField(blank=True, null=True, verbose_name='Processing date')),
                ('finishing_date', models.DateTimeField(blank=True, null=True, verbose_name='Finishing date')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(default='Username', max_length=255, verbose_name='User name')),
            ],
        ),
    ]
