# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-18 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callorder',
            name='name',
            field=models.CharField(max_length=255, verbose_name='User name'),
        ),
    ]
