# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-13 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, '\u043d\u0435 \u043e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d'), (1, '\u043e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d'), (2, '\u0443\u0434\u0430\u043b\u0435\u043d'), (3, '\u043f\u0435\u0440\u0435\u043d\u0435\u0441\u0435\u043d \u0432 \u0447\u0435\u0440\u043d\u043e\u0432\u0438\u043a')], default=3, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, '\u043d\u0435 \u043e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d'), (1, '\u043e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d'), (2, '\u0443\u0434\u0430\u043b\u0435\u043d'), (3, '\u043f\u0435\u0440\u0435\u043d\u0435\u0441\u0435\u043d \u0432 \u0447\u0435\u0440\u043d\u043e\u0432\u0438\u043a')], default=3, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[(b'u', b'User'), (b'm', b'Model'), (b'c', b'Company'), (b'd', b'Dead soul')], max_length=1)),
                ('name', models.CharField(max_length=255, verbose_name=b'Profile name')),
                ('short_description', models.CharField(blank=True, default=b'', max_length=255, null=True, verbose_name=b'Short description')),
                ('description', models.TextField(blank=True, default=b'', null=True, verbose_name=b'Description')),
                ('avatar', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=b'profile_images', verbose_name='Avatar')),
                ('certified', models.BooleanField(default=True, verbose_name=b'Certified by the moderator')),
                ('completed', models.BooleanField(default=False, verbose_name=b'Completed information')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Address')),
                ('position', models.PositiveIntegerField(default=None, null=True, verbose_name='position')),
                ('point', models.PositiveSmallIntegerField(default=0, verbose_name='\u0431\u0430\u043b\u043b\u044b')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name=b'Email')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
            options={
                'verbose_name': 'Email \u043f\u0440\u043e\u0444\u0438\u043b\u044f',
                'verbose_name_plural': 'Email \u043f\u0440\u043e\u0444\u0438\u043b\u044f',
            },
        ),
        migrations.CreateModel(
            name='ProfileHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_str', models.CharField(max_length=255, unique=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, verbose_name=b'Phone number')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
            options={
                'verbose_name': '\u0422\u0435\u043b\u0435\u0444\u043e\u043d \u043f\u0440\u043e\u0444\u0438\u043b\u044f',
                'verbose_name_plural': '\u0422\u0435\u043b\u0435\u0444\u043e\u043d\u044b \u043f\u0440\u043e\u0444\u0438\u043b\u044f',
            },
        ),
        migrations.CreateModel(
            name='ProfileUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Url')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
            options={
                'verbose_name': '\u0421\u0430\u0439\u0442 \u043f\u0440\u043e\u0444\u0438\u043b\u044f',
                'verbose_name_plural': '\u0421\u0430\u0439\u0442\u044b \u043f\u0440\u043e\u0444\u0438\u043b\u044f',
            },
        ),
    ]
