# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-11 19:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        #('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('user_type', models.IntegerField(blank=True, choices=[(1, '\u041c\u043e\u0434\u0435\u043b\u044c'), (2, '\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')], null=True, verbose_name='\u0422\u0438\u043f \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
        ),
        migrations.CreateModel(
            name='BustSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440 \u0433\u0440\u0443\u0434\u0438')),
                ('code', models.CharField(db_index=True, max_length=10, verbose_name='\u041a\u043e\u0434')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0440\u0430\u043d\u0430',
                'verbose_name_plural': '\u0421\u0442\u0440\u0430\u043d\u044b',
            },
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u041e\u0441\u043e\u0431\u043e\u0435')),
                ('code', models.CharField(db_index=True, max_length=10, verbose_name='\u041a\u043e\u0434')),
            ],
        ),
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u0424\u0438\u0433\u0443\u0440\u0430')),
                ('code', models.CharField(db_index=True, max_length=10, verbose_name='\u041a\u043e\u0434')),
            ],
        ),
        migrations.CreateModel(
            name='HairColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u0426\u0432\u0435\u0442 \u0432\u043e\u043b\u043e\u0441')),
                ('code', models.CharField(db_index=True, max_length=10, verbose_name='\u041a\u043e\u0434')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0438\u043a')),
                ('description', models.TextField(blank=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('avalible', models.BooleanField(default=False)),
                ('age', models.PositiveIntegerField(verbose_name='\u0412\u043e\u0437\u0440\u0430\u0441\u0442')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('views_count', models.PositiveIntegerField(verbose_name='\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u044b')),
                ('bust_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.BustSize', verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440 \u0433\u0440\u0443\u0434\u0438')),
                ('extra', models.ManyToManyField(blank=True, to='main.Extra', verbose_name='\u041e\u0441\u043e\u0431\u043e\u0435')),
                ('figure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Figure', verbose_name='\u0424\u0438\u0433\u0443\u0440\u0430')),
                ('hair_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.HairColor', verbose_name='\u0426\u0432\u0435\u0442 \u0432\u043e\u043b\u043e\u0441')),
            ],
        ),
        migrations.CreateModel(
            name='PublicArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0430 \u043f\u043e\u043a\u0430\u0437')),
                ('code', models.CharField(db_index=True, max_length=10, verbose_name='\u041a\u043e\u0434')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u0420\u0430\u0441\u0441\u0430')),
                ('code', models.CharField(db_index=True, max_length=10, verbose_name='\u041a\u043e\u0434')),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u041f\u043e\u043b')),
                ('code', models.CharField(db_index=True, max_length=10, verbose_name='\u041a\u043e\u0434')),
            ],
        ),
        migrations.CreateModel(
            name='SpeaksLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u042f\u0437\u044b\u043a')),
                ('code', models.CharField(db_index=True, max_length=10, verbose_name='\u041a\u043e\u0434')),
            ],
        ),
        migrations.AddField(
            model_name='model',
            name='public_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.PublicArea', verbose_name='\u041d\u0430 \u043f\u043e\u043a\u0430\u0437'),
        ),
        migrations.AddField(
            model_name='model',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Race', verbose_name='\u0420\u0430\u0441\u0441\u0430'),
        ),
        migrations.AddField(
            model_name='model',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Sex', verbose_name='\u041f\u043e\u043b'),
        ),
        migrations.AddField(
            model_name='model',
            name='speaks_language',
            field=models.ManyToManyField(blank=True, to='main.SpeaksLanguage', verbose_name='\u042f\u0437\u044b\u043a'),
        ),
        migrations.AddField(
            model_name='model',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Country', verbose_name='\u0421\u0442\u0440\u0430\u043d\u0430'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterIndexTogether(
            name='model',
            index_together=set([('name', 'avalible', 'views_count')]),
        ),
    ]
