# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-03 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camsnapshot',
            options={'ordering': ('-date_add',)},
        ),
        migrations.AlterField(
            model_name='camservice',
            name='url',
            field=models.CharField(max_length=255, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='model',
            name='profile_image',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430 \u043f\u0440\u043e\u0444\u0438\u043b\u044f'),
        ),
    ]
