# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-14 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170514_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='camservice',
            name='prefix',
            field=models.CharField(default=1, max_length=100, verbose_name='\u041f\u0440\u0435\u0444\u0438\u043a\u0441'),
            preserve_default=False,
        ),
    ]
