# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_camservice_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bustsize',
            name='code',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='\u041a\u043e\u0434'),
        ),
        migrations.AlterField(
            model_name='extra',
            name='code',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='\u041a\u043e\u0434'),
        ),
        migrations.AlterField(
            model_name='figure',
            name='code',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='\u041a\u043e\u0434'),
        ),
        migrations.AlterField(
            model_name='haircolor',
            name='code',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='\u041a\u043e\u0434'),
        ),
        migrations.AlterField(
            model_name='model',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u044b'),
        ),
        migrations.AlterField(
            model_name='publicarea',
            name='code',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='\u041a\u043e\u0434'),
        ),
        migrations.AlterField(
            model_name='race',
            name='code',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='\u041a\u043e\u0434'),
        ),
        migrations.AlterField(
            model_name='speakslanguage',
            name='code',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='\u041a\u043e\u0434'),
        ),
    ]
