# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-17 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170916_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='age',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='\u0412\u043e\u0437\u0440\u0430\u0441\u0442'),
        ),
    ]
