# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-21 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170515_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='camservice',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default=1, upload_to='camservice', verbose_name='\u0418\u043a\u043e\u043d\u043a\u0430'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='model',
            name='age',
            field=models.PositiveIntegerField(default=0, verbose_name='\u0412\u043e\u0437\u0440\u0430\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='sex',
            name='code',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='\u041a\u043e\u0434'),
        ),
    ]
