# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-17 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170917_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='bay_online_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
