# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-21 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170521_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='display_name',
            field=models.CharField(default=1, max_length=100, verbose_name='\u041d\u0438\u043a'),
            preserve_default=False,
        ),
    ]
