# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-22 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_model_bay_online_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='camservice',
            name='on_header',
            field=models.BooleanField(default=True),
        ),
    ]
