# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-13 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0442\u0435\u0433\u0430')),
                ('certified', models.BooleanField(default=True, verbose_name=b'Certified by the moderator')),
            ],
        ),
        migrations.CreateModel(
            name='TagCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_key', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='\u041a\u043b\u044e\u0447 \u0434\u043b\u044f \u0441\u0432\u044f\u0437\u0438 \u0438\u0442\u0435\u043c\u043e\u0432 \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0430 \u0441 \u0442\u0435\u0433\u0430\u043c\u0438')),
                ('title', models.CharField(max_length=255, verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430 \u0442\u0435\u0433\u043e\u0432')),
            ],
        ),
        migrations.CreateModel(
            name='TagColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255, verbose_name=b'Color')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tags.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.TagCatalog'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('title',)]),
        ),
    ]
