# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-07 21:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtype', models.IntegerField(choices=[(0, '\u0441\u043e\u0432\u043f\u0430\u0434\u0435\u043d\u0438\u0435'), (1, '\u043d\u0430\u0447\u0438\u043d\u0430\u0435\u0442\u0441\u044f \u0441'), (2, '\u0437\u0430\u043a\u0430\u043d\u0447\u0438\u0432\u0430\u0435\u0442\u0441\u044f \u043d\u0430'), (3, '\u0441\u043e\u0434\u0435\u0440\u0436\u0438\u0442')], verbose_name='\u0442\u0438\u043f')),
                ('pattern', models.TextField(verbose_name='\u043f\u0430\u0442\u0442\u0435\u0440\u043d')),
                ('title', models.TextField(blank=True, help_text='150 \u0441\u0438\u043c\u0432\u043e\u043b\u043e\u0432 \u043c\u0430\u043a\u0441\u0438\u043c\u0443\u043c.', validators=[django.core.validators.MaxLengthValidator(150)], verbose_name='<title>')),
                ('keywords', models.TextField(blank=True, help_text='250 \u0441\u0438\u043c\u0432\u043e\u043b\u043e\u0432 \u043c\u0430\u043a\u0441\u0438\u043c\u0443\u043c.', validators=[django.core.validators.MaxLengthValidator(250)], verbose_name='<meta name="keywords">')),
                ('description', models.TextField(blank=True, help_text='200 \u0441\u0438\u043c\u0432\u043e\u043b\u043e\u0432 \u043c\u0430\u043a\u0441\u0438\u043c\u0443\u043c.', validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='<meta name="description">')),
                ('enabled', models.BooleanField(default=True, verbose_name='\u0440\u0430\u0431\u043e\u0442\u0430\u0435\u0442')),
            ],
            options={
                'verbose_name': '\u043f\u0440\u0430\u0432\u0438\u043b\u043e',
                'verbose_name_plural': '\u043f\u0440\u0430\u0432\u0438\u043b\u0430',
            },
        ),
    ]
